# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e06b14fd4721de94191810674ac3fcdbdbc750095efae35f1d6630c8fe0d7dcacc4f2b677f76e068376ba45a83f1e4f35692c34d82faf28487bff58f34ef444d

test:
  secret_key_base: eea33fdab7f64e0b4c2588756cd62ab7a0d7dcb0f5d10e6fb9015c86ac0eb613f5a931bac4d529a5c51d1dfe72fb47fa2360c34628fdc6bd495865aec3b20eac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
